type = "js"
main = "server/_keep.mjs"
client-main = "client/client.js"
client-files = [ 
    "client/*",
    "client/objectList.html"
]
dependencies = ["natives"]

[client-scripts]
esm = true

[server-scripts]
esm = true